version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Pre-Cache
          command: cp yarn.lock cacheKey
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "cacheKey" }}
          - v1-dependencies-
      - run:
          name: Install NPM Packages
          command: yarn install
      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "cacheKey" }}
      - run:
          name: Test
          command: yarn test
